### ISSUE TITLE
Question about preprocessing MPII_INF_3DHP?

### ISSUE THREAD

**Issue by leechaonao** [zczcwh/PoseFormer#10]
could you give me the details about preprocessing the MPII_INF_3DHP dataset? I follow this script  **https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/mpii3d_utils.py**  to preprocess the dataset and train with lr=0.0004, batch_size=512, frame=9, I got much smaller results(**MPJPE:50mm**) than your paper. is it corrected?

**Comment by zczcwh** [comment]
@leechaonao  I didn't follow the script you mentioned (VIBE), I don't know if this is correct or not.  I use someone else's code and sorry, I don't have permission to redistribute.

**Comment by flyyyyer** [comment]
Do you use the training set of 3dhp to train the model or just test the testing set of 3dhp on a Human3.6M pretraind model?
