### ISSUE TITLE
ValueError on  Custom Video Visualization

### ISSUE THREAD

**Issue by nies14** [zczcwh/PoseFormer#17]
ValueError: non-broadcastable output operand with shape (1621,1,17,3) doesn't match the broadcast shape (1621,1621,17,3)

$ python run_poseformer.py -k cpn_ft_h36m_dbb -c checkpoint --evaluate pretrained_h36m_cpn.bin --render --viz-subject S1 --viz-action Directions --viz-camera 0 --viz-video "/home/user/Desktop/Test/PoseFormer-main/data/Video/Directions.mp4" --viz-output output.gif --viz-size 3 --viz-downsample 2 --viz-limit 60

Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 81 frames
INFO: Trainable parameter count: 9602885
Loading checkpoint checkpoint/pretrained_h36m_cpn.bin
INFO: Testing on 225676 frames
Rendering...
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/user/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/user/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/user/anaconda3/envs/pose2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/Desktop/Test/PoseFormer-main/run_poseformer.py", line 606, in <module>
    prediction += trajectory
ValueError: non-broadcastable output operand with shape (1621,1,17,3) doesn't match the broadcast shape (1621,1621,17,3)

**Comment by SnickerFritz** [comment]
Hi, you'll need to reshape the prediction vector in the run_poseformer.py file.

I believe this is line 598-601, you'll want to add this:
    gen = UnchunkedGenerator(None, [ground_truth], [input_keypoints],
                             pad=pad, causal_shift=causal_shift, augment=args.test_time_augmentation,
                             kps_left=kps_left, kps_right=kps_right, joints_left=joints_left, joints_right=joints_right)
    prediction = evaluate(gen, return_predictions=True)
    prediction = prediction[:,0,:,:]

**Comment by nies14** [comment]
Hi, thanks for the reply. But unfortunately, it doesn't show the correct output. I also tried to use squeeze() only in line number 542. Both give the same output.

![output](https://user-images.githubusercontent.com/27515470/139780515-a829d6c2-9530-402e-8efe-0427973b1150.gif)

**Comment by SnickerFritz** [comment]
What is the stated error values that you get from this evaluation? 
There are visual errors that dont seem to check out, while your 3d GT and 2d detector seem right. 

I trained a system on Human3.6 for 17 frames and got the output below.
![Transformer_output](https://user-images.githubusercontent.com/35127627/139786122-71889ca8-b7f2-42e6-9d0d-bd559c12ed48.gif)
s.
![image](https://user-images.githubusercontent.com/35127627/139786276-6149fb79-6c3c-4d7e-b0e2-355d14aa9288.png)

**Comment by nies14** [comment]
Actually, I don't get any errors. I am using 'pretrained_h36m_cpn.bin' as checkpoint. Could that be an issue?
When I use best_epoch.bin as checkpoint it gives me the proper output.

I'm getting the following output for visualization using  'pretrained_h36m_cpn.bin' as checkpoint
"Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 27 frames
INFO: Trainable parameter count: 9573455
Loading checkpoint checkpoint/best_epoch.bin
INFO: Testing on 248376 frames
Rendering...
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/user/Desktop/Test/PoseFormer-main/data/Video/Walking.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : 2021/10/03 00:54:29
    encoder         : Lavf58.76.100
  Duration: 00:00:04.45, start: 0.000000, bitrate: 3850 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1000x1002 [SAR 1:1 DAR 500:501], 3846 kb/s, 27 fps, 27 tbr, 13824 tbn, 54 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    date            : 2021/10/03 00:54:29
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1000x1002 [SAR 1:1 DAR 500:501], q=2-31, 649296 kb/s, 27 fps, 27 tbn, 27 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 rawvideo
frame=  120 fps=0.0 q=-0.0 Lsize=  352266kB time=00:00:04.44 bitrate=649296.1kbits/s speed=13.5x    
video:352266kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
/home/user/Desktop/Test/PoseFormer-main/common/visualization.py:205: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. "

**Comment by SnickerFritz** [comment]
> Actually, I don't get any errors. I am using 'pretrained_h36m_cpn.bin' as checkpoint. Could that be an issue?

Yes. Use 'detected81f' or 'gt81f' if you can evaluate 81 frames.
Could you clarify where you got 'best_epoch.bin' from?
I believe you got 'best_epoch.bin' from the training in PoseFormer, is that correct? 

Could you clarify where you got 'pretrained_h36m_cpn.bin' from? 
I believe the 'pretrained_h36m_cpn.bin' you're running is from VideoPose3D, which is a different structure than PoseFormer. If so, I'm surprised PoseFormer it was even able to evaluate those weights.

**Comment by nies14** [comment]
> Could you clarify where you got 'best_epoch.bin' from? I believe you got 'best_epoch.bin' from the training in PoseFormer, is that correct?
> 
> Could you clarify where you got 'pretrained_h36m_cpn.bin' from? I believe the 'pretrained_h36m_cpn.bin' you're running is from VideoPose3D, which is a different structure than PoseFormer. If so, I'm surprised PoseFormer it was even able to evaluate those weights.

Yes, both of your assumptions are correct. It was my bad to use the pretrained_h36m_cpn.bin as checkpoint. Thanks a lot for your help.
