### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 123guozhiyu** [zczcwh/PoseFormer#5]
I can't find the Dataset. Would you like to share me ? 
my email: 3509251484@qq.com
Thank you !

**Comment by zczcwh** [comment]
@123guozhiyu We don't have permission to redistribute. Please follow the VideoPose3d's instructions to prepare the dataset. (https://github.com/facebookresearch/VideoPose3D/blob/master/DATASETS.md) 

They provide the detected 2D pose npz file as input. For GT 2D pose and GT 3D pose, you need to download the dataset from the official website and follow the instruction to get the npz file.
