### ISSUE TITLE
question about preprocessing

### ISSUE THREAD

**Issue by shoutOutYangJie** [zczcwh/PoseFormer#6]
I notice you use "norm_coordinate_screnn" to preprocess data. But I don't know whether the coordinates of the original points are absolute coordinate on the original image or not.  Because I notice your method just processes a single human pose, the original coordinate before "norm_coordinate_screnn" is just absolute coordinate or processed coordinate?

**Comment by zczcwh** [comment]
@shoutOutYangJie , We follow the same data preprocessing as VideoPose3D (https://github.com/facebookresearch/VideoPose3D). Please refer to VideoPose3D for more detailed information.
