### ISSUE TITLE
Learning Curves

### ISSUE THREAD

**Issue by hankhuynh1011** [zczcwh/PoseFormer#8]
Hi, 
Could you provide the Train and test Learning Curves for 27f, or when it could get ~47mm, I try to run your code:
    python run_poseformer.py -k cpn_ft_h36m_dbb -f 27 -lr 0.00004 -lrd 0.99
util epoch 28, the 3d_valid is just 51.88954.
Sorry because my GPU too weak, it takes me too long time.

Thanks, best regards.

**Comment by hankhuynh1011** [comment]
This is my training log:
** The final evaluation will be carried out after the last training epoch.
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0866[1] time 140.46 lr 0.000040 3d_train 86.757826 3d_eval 61.918563 3d_valid 66.374079
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0524[2] time 141.37 lr 0.000040 3d_train 52.431001 3d_eval 51.101789 3d_valid 59.368456
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0434[3] time 141.34 lr 0.000039 3d_train 43.430816 3d_eval 47.254948 3d_valid 57.863754
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0386[4] time 141.36 lr 0.000039 3d_train 38.570824 3d_eval 44.399304 3d_valid 58.072027
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0353[5] time 141.37 lr 0.000038 3d_train 35.303323 3d_eval 41.959436 3d_valid 55.760189
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0328[6] time 141.36 lr 0.000038 3d_train 32.792828 3d_eval 39.704795 3d_valid 55.975205
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0308[7] time 141.50 lr 0.000038 3d_train 30.788244 3d_eval 38.325394 3d_valid 55.239136
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0291[8] time 141.61 lr 0.000037 3d_train 29.105779 3d_eval 36.961202 3d_valid 55.645896
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0277[9] time 141.83 lr 0.000037 3d_train 27.682119 3d_eval 36.123469 3d_valid 54.999914
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0264[10] time 141.82 lr 0.000037 3d_train 26.440864 3d_eval 35.087686 3d_valid 54.741330
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0253[11] time 141.75 lr 0.000036 3d_train 25.349924 3d_eval 34.463552 3d_valid 54.969667
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0244[12] time 141.29 lr 0.000036 3d_train 24.384628 3d_eval 32.881129 3d_valid 54.910784
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0235[13] time 141.03 lr 0.000035 3d_train 23.544576 3d_eval 32.451128 3d_valid 54.266661
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0228[14] time 140.77 lr 0.000035 3d_train 22.775536 3d_eval 31.344421 3d_valid 53.632880
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0221[15] time 140.79 lr 0.000035 3d_train 22.074822 3d_eval 30.812765 3d_valid 53.793558
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0215[16] time 140.80 lr 0.000034 3d_train 21.457081 3d_eval 30.373356 3d_valid 53.750149
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0209[17] time 140.81 lr 0.000034 3d_train 20.881110 3d_eval 30.037761 3d_valid 53.497580
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0204[18] time 140.92 lr 0.000034 3d_train 20.355580 3d_eval 28.784014 3d_valid 52.927281
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0199[19] time 141.43 lr 0.000033 3d_train 19.873033 3d_eval 28.625125 3d_valid 53.005290
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0194[20] time 141.55 lr 0.000033 3d_train 19.430529 3d_eval 27.895763 3d_valid 52.235128
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0190[21] time 141.23 lr 0.000033 3d_train 19.011732 3d_eval 27.660354 3d_valid 52.443241
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0186[22] time 141.46 lr 0.000032 3d_train 18.634735 3d_eval 26.529928 3d_valid 52.231708
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0183[23] time 141.37 lr 0.000032 3d_train 18.282781 3d_eval 26.775029 3d_valid 52.374747
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0180[24] time 141.34 lr 0.000032 3d_train 17.952975 3d_eval 26.310366 3d_valid 52.308301
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0176[25] time 141.41 lr 0.000031 3d_train 17.643346 3d_eval 26.024666 3d_valid 52.156781
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0174[26] time 141.33 lr 0.000031 3d_train 17.351704 3d_eval 25.414759 3d_valid 51.634511
save best checkpoint
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0171[27] time 141.47 lr 0.000031 3d_train 17.083208 3d_eval 25.317480 3d_valid 52.245745
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0168[28] time 141.21 lr 0.000030 3d_train 16.833050 3d_eval 25.207126 3d_valid 51.889547
6092/6093 [============================>.] - ETA: 1s - loss_trn: 0.0166[29] time 141.43 lr 0.000030 3d_train 16.590010 3d_eval 25.063257 3d_valid 52.481093

Thanks

**Comment by zczcwh** [comment]
@hankhuynh1011 Sorry, I didn't save the learning curve. In your case, you can try to use a big lr (such as 0.0004) for maybe 20 epoch, then use the best model to resume training with low lr. 
Also, the MPJPE shows here is not the final MPJPE reported in the paper (here is frame-wise MPJPE not action-wise MPJPE). You need to use the evaluation code to get the final MPJPE value.

**Comment by hankhuynh1011** [comment]
oh, I got it, thank you so much, I will try as your recommendation

**Comment by flyyyyer** [comment]
> oh, I got it, thank you so much, I will try as your recommendation

Could you reproduced the results as the paper said ?

**Comment by hankhuynh1011** [comment]
I can not @@

**Comment by alecda573** [comment]
@flyyyyer @zczcwh @hankhuynh1011 @cc1164 was anyone able to reproduce the results from paper on detections for either 9,  27, or 81 frame models?

**Comment by chentianyangWHU** [comment]
> @flyyyyer @zczcwh @hankhuynh1011 @cc1164 was anyone able to reproduce the results from paper on detections for either 9, 27, or 81 frame models?

I got 50.3mm with f=9 in training and 49.8mm using its evaluation code (even 0.1 mm smaller than what was repotered in paper). However, I get larger error when it comes to f=27 (53.6mm) and f=81(even larger).

**Comment by Ared521** [comment]
> frame-wise MPJPE 而不是 action-wise MPJPE

Hello, what is the difference between frame-wise MPJPE and action-wise MPJPE?
