### ISSUE TITLE
Unable to resolve anaconda packages to setup environment

### ISSUE THREAD

**Issue by fortminors** [zczcwh/PoseFormer#9]
When running

$ conda env create -f poseformer.yml

I get this output:

> (base) D:\Desktop\PoseFormer-main>conda env create -f poseformer.yml
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
>   - pyyaml==5.3.1=py38h7b6447c_1
>   - mkl-service==2.3.0=py38he904b0f_0
>   - xorg-xproto==7.0.31=h14c3975_1007
>   - cudatoolkit==11.0.221=h6bb024c_0
>   - libffi==3.2.1=hf484d3e_1007
>   - wrapt==1.12.1=py38h7b6447c_1
>   - matplotlib-base==3.3.2=py38h91b0d89_0
>   - nss==3.57=he751ad9_0
>   - libedit==3.1.20191231=h14c3975_1
>   - readline==8.0=h7b6447c_0
>   - tensorflow-base==2.2.0=mkl_py38h5059a2d_0
>   - pillow==7.2.0=py38hb39fc2d_0
>   - libtiff==4.1.0=h2733197_1
>   - gst-plugins-base==1.14.5=h0935bb2_2
>   - tornado==6.0.4=py38h7b6447c_1
>   - expat==2.2.9=he6710b0_2
>   - jpeg==9d=h516909a_0
>   - lz4-c==1.9.2=he6710b0_1
>   - nspr==4.29=he1b5a44_0
>   - kiwisolver==1.2.0=py38hbf85e49_0
>   - scipy==1.5.2=py38h0b6359f_0
>   - fontconfig==2.13.1=h1056068_1002
>   - psutil==5.7.2=py38h7b6447c_0
>   - libwebp-base==1.1.0=h7b6447c_3
>   - mysql-libs==8.0.21=hf3661c5_2
>   - gmp==6.2.0=he1b5a44_2
>   - python==3.8.2=hcf32534_0
>   - cffi==1.14.0=py38h2e261b9_0
>   - qt==5.12.9=h1f2b2cb_0
>   - libsodium==1.0.18=h7b6447c_0
>   - mkl_random==1.1.1=py38h0573a6f_0
>   - libevent==2.1.10=hcdb4288_2
>   - jasper==1.900.1=hd497a04_4
>   - krb5==1.17.1=h173b8e3_0
>   - freetype==2.10.2=h5ab3b9f_0
>   - libllvm10==10.0.1=hbcb73fb_5
>   - openssl==1.1.1i=h27cfd23_0
>   - libuuid==2.32.1=h14c3975_1000
>   - libpng==1.6.37=hbc83047_0
>   - pcre==8.44=he6710b0_0
>   - libiconv==1.16=h516909a_0
>   - pyzmq==19.0.2=py38he6710b0_1
>   - xorg-kbproto==1.0.7=h14c3975_1002
>   - tensorflow==2.2.0=mkl_py38h6d3daf0_0
>   - brotlipy==0.7.0=py38h7b6447c_1000
>   - certifi==2020.12.5=py38h06a4308_0
>   - pytorch==1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
>   - aiohttp==3.7.2=py38h1e0a361_0
>   - sqlite==3.33.0=h62c20be_0
>   - lame==3.100=h7b6447c_0
>   - libgcc-ng==9.1.0=hdf63c60_0
>   - ld_impl_linux-64==2.33.1=h53a641e_7
>   - libxcb==1.14=h7b6447c_0
>   - nettle==3.4.1=hbb512f6_0
>   - xorg-libx11==1.6.12=h516909a_0
>   - icu==67.1=he1b5a44_0
>   - cairo==1.16.0=h3fc0475_1005
>   - pixman==0.38.0=h7b6447c_0
>   - ca-certificates==2021.1.19=h06a4308_0
>   - libxkbcommon==0.10.0=he1b5a44_0
>   - ninja==1.10.1=py38hfd86e86_0
>   - xz==5.2.5=h7b6447c_0
>   - zeromq==4.3.2=he6710b0_3
>   - numpy-base==1.19.2=py38hfa32c7d_0
>   - gnutls==3.6.13=h79a8f9a_0
>   - libprotobuf==3.13.0=hd408876_0
>   - dbus==1.13.16=hb2f20db_0
>   - glib==2.63.1=h5a9c865_0
>   - libuv==1.40.0=h7b6447c_0
>   - libpq==12.3=h5513abc_0
>   - gstreamer==1.14.5=h36ae1b5_2
>   - multidict==4.7.5=py38h1e0a361_2
>   - xorg-libice==1.0.10=h516909a_0
>   - protobuf==3.13.0=py38he6710b0_1
>   - mkl_fft==1.2.0=py38h23d657b_0
>   - libstdcxx-ng==9.1.0=hdf63c60_0
>   - yarl==1.6.2=py38h1e0a361_0
>   - cython==0.29.21=py38he6710b0_0
>   - x264==1!152.20180806=h7b6447c_0
>   - libxml2==2.9.10=h68273f3_2
>   - lcms2==2.11=h396b838_0
>   - grpcio==1.33.2=py38heead2fc_0
>   - harfbuzz==2.7.2=hee91db6_0
>   - zstd==1.4.5=h9ceee32_0
>   - h5py==2.10.0=py38hd6299e0_1
>   - bzip2==1.0.8=h7b6447c_0
>   - pandas==1.1.1=py38he6710b0_0
>   - c-ares==1.16.1=h516909a_3
>   - tk==8.6.10=hbc83047_0
>   - xorg-xextproto==7.3.0=h14c3975_1002
>   - yaml==0.2.5=h7b6447c_0
>   - hdf5==1.10.6=hb1b8bf9_0
>   - libclang==10.0.1=default_hb85057a_2
>   - xorg-libsm==1.2.3=h84519dc_1000
>   - xorg-libxext==1.3.4=h516909a_0
>   - xorg-libxrender==0.9.10=h516909a_1002
>   - openh264==2.1.1=h8b12597_0
>   - xorg-renderproto==0.11.1=h14c3975_1002
>   - libgfortran-ng==7.3.0=hdf63c60_0
>   - ncurses==6.2=he6710b0_1
>   - cryptography==3.1.1=py38h1ba5d50_0
>   - zlib==1.2.11=h7b6447c_3
>   - graphite2==1.3.14=h23475e2_0

Is there a way to fix this? Thanks!

**Comment by zczcwh** [comment]
@fortminors Are you using Windows systems? The poseformer.yml I provided is based on Ubuntu, maybe some packages do not support the Windows system. I'm not quite familiar with this.

**Comment by fortminors** [comment]
@zczcwh Yes, sorry I should've mentioned that. I am using Windows. Would it be possible to test the demo on Windows machine? Should I be trying to find a workaround for this (possibly finding substitution packages for Win10) ?

**Comment by zczcwh** [comment]
@fortminors , You can try, but I didn't test this on Windows. Sorry, maybe I can not help with Windows issues.
